title: RTFM srl
author: RTFM
description: |
  Software development, DevOps, Smart Contracts and LLM.

baseurl: ""
url: "https://www.rtfm.srl"

# social links
# twitter_username:
# github_username: 
# facebook_username:
# instagram_username:
# linkedin_username:
# rss: rss

# integrations
#disqus:
#  shortname:

# others
permalink: /:year/:title/
timezone: Europe/Rome

theme: jekyll-theme-hydeout
plugins:
  - jekyll-seo-tag
